require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
